apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: signadot
  name: sd-mariadb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: signadot
  name: sd-mariadb
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: signadot
  name: sd-mariadb
subjects:
- kind: ServiceAccount
  namespace: signadot
  name: sd-mariadb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sd-mariadb